### ISSUE TITLE
Error: Invalid URL character '#' at position..

### ISSUE THREAD

**Issue by opensrc-ai** [vitaly-t/connection-string#42] opened 2020-08-18 04:32 UTC
Running into an error where if the password for the connection string starts with a '#' then it throws an error, was wondering if someone else found a work around for this.

**Comment by vitaly-t** [comment] 2020-08-18 04:37
Duplicate of #15, #35
---
Password must be URL-encoded. Code for `#` is `%23`.

**Closed by vitaly-t** 2020-08-18 04:37 UTC

**Comment by vitaly-t** [comment] 2020-08-18 11:13
The easiest to get it right is to run this:

```js
console.log(encodeURIComponent('my-password'));
```

**Comment by vitaly-t** [comment] 2020-08-28 08:44
Added in **FAQ:** [https://github.com/vitaly-t/connection-string/wiki/FAQ#how-to-use-special-symbols-for-user-name-or-password](How to use special symbols for user name or password?).

**Comment by markstos** [comment] 2021-08-20 19:09
The FAQ could improved. While it could be helpful to leave the heading vaguely referring to "special symbols" the description could be more precise:

>  Reserved characters for percent encoding must be escaped in URIs. The full list of reserved characters from RFC 3986 is: 

     !	#	$	&	'	(	)	*	+	,	/	:	;	=	?	@	[	]

Percent encoding is also known as URL-encoding.  The percent encoded versions of these characters are given below:

    ... [ include list here ]
