### ISSUE TITLE
Error when password has @

### ISSUE THREAD

**Issue by datvq** [vitaly-t/connection-string#35] opened 2020-06-14 14:02 UTC
My password has '@'. :D

**Comment by vitaly-t** [comment] 2020-06-14 17:02
And?

Duplicate of #15

**Closed by vitaly-t** 2020-06-14 17:02 UTC

**Comment by vitaly-t** [comment] 2020-08-28 08:45
Added in **FAQ -** [How to use special symbols for user name or password?](https://github.com/vitaly-t/connection-string/wiki/FAQ#how-to-use-special-symbols-for-user-name-or-password)
